services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FGTCLB\CategoryTypes\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*.php'

  cache.category_types:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['category_types']

  FGTCLB\CategoryTypes\Registry\CategoryTypeRegistry:
    factory:
      - '@FGTCLB\CategoryTypes\Loader\CategoryTypeLoader'
      - 'load'